### ISSUE TITLE
Event Location Status?

### ISSUE THREAD

**Issue by Jamafie** [swiss-art-research-net/crmaaa#43]
I think if we add this, we'll have pretty much covered the  gambit of possible locations, as we already have Physical Locative Status, Residential Status and Topographical Status, hitting all the high level cidoc disjoints... agreed @Habennin ?

**Comment by Jamafie** [comment]
This might also let us account for the fact that an event happened in, say the UK circa 1800-whatever, and in Ireland post 1916, despite the actual data of the event... 
... could finally get this bugbear off our backs!

**Comment by Habennin** [comment]
I see the appeal. So Event Location Status is where it is taken to have been rather than where it space time volume wise is asserted to actually have been. Those two sets of facts may or may not coincide. 

Do we have a catchy example for this? I agree it would then gives us a complete set of tools for handling the CRM disjoints and their relation to space. I had hesitated before because it really hits the 'constructivist' notes. But we have already done it for physical thing and I think for good reason (see for example permanent location which may never be realized so it never was a spacetime volume fact, it was always a social fact). 

I don't quite catch the UK vs Ireland example above.  Can you spell if out more?

Maybe an example like the signing of a treaty between two different groups on contested land. The signing happens in relation to different places according to their different cultural perspective. Another cultural perspective is the space time volume perspective...

**Comment by Jamafie** [comment]
@Habennin , the point is the E53 is already constructivist. Look at the scope notes, it's written there in black and white. A place is only a place by virtue of the borders that are assigned to it (i.e., our ability to bound it, whether by coordinates or with a name). This is case of social fact par excellence.
I put it to you otherwise: give me an example of a place that is not a social fact? 
My example is meant to draw this out - we may not disagree about about 'where' something happened - I can stand there and say this is where it happened - but that 'where' may be variously defined. The location of something may not have changed in and of itself but the 'where' of the location has, when for example a new country (like Ireland, Ukraine, etc,) comes into existence.
